---
phases:
  build:
    commands:
      - "echo Build started on `date`"
      - "echo Building the Docker image..."
      - "docker build -t mahammadism/new_app:latest ."
      - "docker tag mahammadism/new_app:latest mahammadism/new_app:latest"
  post_build:
    commands:
      - "echo Build completed on `date`"
      - "echo Pushing the Docker image..."
      - "docker push mahammadism/new_app:latest"
  pre_build:
    commands:
      - "echo Logging in to Docker Hub..."
      - "docker login --username=\"mahammadism\" --password=\"ismail@1985\""
version: 0.1
